### ISSUE TITLE
Arnes

### ISSUE THREAD

**Issue by sysmat** [1katoda/SerialReader1#1]
Pozdravljen,

Hvala za hitro odzivnost, smo malo pogledali projekt pa ga izboljšali.
Če se strinjaš bi preko zahtevkov tukaj na github-u preoblikovali projekt, na ta način bi dobili še boljši vpogled v tvoje sposobnosti hitrega učenja

**Comment by 1katoda** [comment]
Pozdravljeni, 
seveda, z veseljem sprejmem vse izboljsave, iz katerih se lahko kaj vec naucim.

**Comment by sysmat** [comment]
No, super pol pa kar začnimo
